In [1]:
import pandas as pd
data = pd.read_csv("../Data/gpascore.csv")
data.head()

admit    gre   gpa  rank
0      0  380.0  3.21     3
1      1  660.0  3.67     3
2      1  800.0  4.00     1
3      1  640.0  3.19     4
4      0  520.0  2.33     4

admit : 합격여부    
gre : 영어성적    
gpa : 학점    
rank : 지원 대학원 수준

# Preprocessing(전처리)

In [2]:
# 결측치 처리
data.isna().sum()

admit    0
gre      1
gpa      0
rank     0
dtype: int64

In [3]:
# 결측치 데이터 삭제
data.dropna(inplace=True)

# 결측치 데이터를 다른 값으로 대체
data.fillna(100)

admit    gre   gpa  rank
0        0  380.0  3.21     3
1        1  660.0  3.67     3
2        1  800.0  4.00     1
3        1  640.0  3.19     4
4        0  520.0  2.33     4
..     ...    ...   ...   ...
421      1  750.0  3.44     4
422      1  710.0  3.66     4
423      0  450.0  3.25     4
424      1  760.0  3.76     2
425      1  710.0  3.82     3

[425 rows x 4 columns]

In [4]:
# 결측치 삭제 확인
data.isna().sum()

admit    0
gre      0
gpa      0
rank     0
dtype: int64

In [5]:
# rank의 종류 파악
sorted(data['rank'].unique())

[1, 2, 3, 4]

In [6]:
# 영어 점수의 최소값과 최대값
print('최대값 :',data['gre'].max())
print('최대값 :',data['gre'].min())

최대값 : 800.0
최대값 : 220.0


In [7]:
# Training Data
x = data[['gre','gpa','rank']]
x.head()

gre   gpa  rank
0  380.0  3.21     3
1  660.0  3.67     3
2  800.0  4.00     1
3  640.0  3.19     4
4  520.0  2.33     4

In [8]:
# target Data
y = data['admit']
y.head()

0    0
1    1
2    1
3    1
4    0
Name: admit, dtype: int64

In [ ]:
# 데이터 갯수 확인
x.count()

gre     425
gpa     425
rank    425
dtype: int64

---
# Deep Learning Model 만들기

In [9]:
from tensorflow import keras

In [10]:
input_layer = keras.layers.InputLayer(input_shape=(3,))
hidden_layer = keras.layers.Dense(256,activation='tanh')
output_layer = keras.layers.Dense(1,activation='sigmoid')

In [11]:
model = keras.Sequential(
    [
        input_layer,
        hidden_layer,
        output_layer
    ]
)

Metal device set to: Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB



2022-07-20 10:54:01.314655: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-07-20 10:54:01.314961: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [12]:
# 손실함수
model.compile(optimizer='adam',loss='binary_crossentropy', metrics='accuracy')
# Opimaizer : learning rate를 알맞게 조정해줌
# - adam
# - adgred
# - adadelta
# - rmsprop
# - sgd
# loss : 손실함수
# - binary-crossentropy : 분류 및 확률 예측 
# metrics : 모델의 평가 기준

In [22]:
# 학습시키기
import numpy as np
model.fit(np.array(x), np.array(y), epochs=500)

Epoch 1/500
14/14 [==============================] - 0s 6ms/step - loss: 0.6330 - accuracy: 0.6306
Epoch 2/500
14/14 [==============================] - 0s 6ms/step - loss: 0.6377 - accuracy: 0.6259
Epoch 3/500
14/14 [==============================] - 0s 6ms/step - loss: 0.6399 - accuracy: 0.6306
Epoch 4/500
14/14 [==============================] - 0s 5ms/step - loss: 0.6453 - accuracy: 0.6518
Epoch 5/500
14/14 [==============================] - 0s 7ms/step - loss: 0.6284 - accuracy: 0.6282
Epoch 6/500
14/14 [==============================] - 0s 6ms/step - loss: 0.6378 - accuracy: 0.6494
Epoch 7/500
14/14 [==============================] - 0s 5ms/step - loss: 0.6296 - accuracy: 0.6518
Epoch 8/500
14/14 [==============================] - 0s 6ms/step - loss: 0.6339 - accuracy: 0.6353
Epoch 9/500
14/14 [==============================] - 0s 6ms/step - loss: 0.6355 - accuracy: 0.6259
Epoch 10/500
14/14 [==============================] - 0s 5ms/step - loss: 0.6399 - accuracy: 0.6118
Epoch 11/

In [23]:
# hidden layer의 가중치 값 출력
hidden_layer.get_weights()[0]

array([[ 2.06520744e-02, -3.94312367e-02,  1.48578119e+00,
         2.10057925e-02, -9.21008438e-02,  2.15523876e-02,
         2.25626882e-02, -7.32416660e-02,  1.66637301e+00,
         1.09606302e+00, -5.31490222e-02,  2.20631957e-02,
         1.81776192e-02,  9.77332473e-01, -5.59244156e-02,
        -1.38797183e-02,  2.17733979e-01, -1.42629817e-01,
         2.14637872e-02, -1.32527143e-01, -4.24058475e-02,
         1.35212075e-02, -6.78080842e-02, -3.90613489e-02,
         1.24716042e-02,  2.57162470e-02,  1.57215583e+00,
        -1.28569067e-01,  1.27623798e-02, -1.68345626e-02,
        -6.40711933e-02,  1.56310141e+00,  1.10428333e+00,
        -8.39002132e-02, -1.22362256e-01, -4.10991460e-02,
         1.62440240e+00,  1.46029854e+00, -1.23609155e-01,
         2.11251713e-02,  1.66704130e+00, -1.69851575e-02,
         1.72287133e-02,  2.42302790e-02, -9.04500186e-02,
         2.36285646e-02, -3.55996713e-02, -1.22657932e-01,
        -1.36156946e-01, -1.09244762e-02, -8.60596150e-0

In [24]:
hidden_layer.get_weights()[1]

array([ 2.93589495e-02, -1.81193009e-05, -3.29451519e-04,  7.93969929e-02,
        0.00000000e+00,  1.47747621e-02,  3.26579213e-02,  0.00000000e+00,
       -3.07627255e-04, -3.39780352e-04,  0.00000000e+00,  5.93247339e-02,
        5.94750047e-02, -3.41502688e-04,  0.00000000e+00, -7.83520490e-02,
       -3.45688808e-04,  0.00000000e+00,  1.82206482e-02,  0.00000000e+00,
       -2.36063897e-05,  1.03901945e-01,  0.00000000e+00, -9.27891961e-05,
        2.89193958e-01,  1.68820973e-02, -3.22456763e-04,  0.00000000e+00,
        1.23804443e-01, -8.37097988e-02,  0.00000000e+00, -3.25525762e-04,
       -3.40117433e-04,  0.00000000e+00,  0.00000000e+00, -1.24882630e-04,
       -3.18615435e-04, -3.27868795e-04,  0.00000000e+00,  7.51386508e-02,
       -3.09388881e-04, -7.04087615e-02,  3.76138240e-02,  2.41442993e-02,
        0.00000000e+00,  1.62120853e-02, -1.20846991e-04,  0.00000000e+00,
        0.00000000e+00, -3.55188996e-01,  0.00000000e+00,  0.00000000e+00,
       -3.24621244e-04,  

In [18]:
# hidden layer의 출력 확인하기
intermediate_layer_model = keras.Model(inputs=model.input,outputs=model.layers[0].output)
intermediate_output = intermediate_layer_model(np.array(x))

In [19]:
intermediate_output

<tf.Tensor: shape=(425, 256), dtype=float32, numpy=
array([[ 1.        , -1.        ,  0.99999994, ...,  0.99999994,
        -1.        , -0.99989724],
       [ 0.99999994, -1.        ,  0.99999994, ...,  0.99999994,
        -1.        , -1.        ],
       [ 0.99999994, -1.        ,  0.99999994, ...,  0.99999994,
        -1.        , -1.        ],
       ...,
       [ 0.99999994, -1.        ,  0.99999994, ...,  0.99999994,
        -1.        , -0.9999848 ],
       [ 0.99999994, -1.        ,  0.99999994, ...,  0.99999994,
        -1.        , -1.        ],
       [ 0.99999994, -1.        ,  0.99999994, ...,  0.99999994,
        -1.        , -1.        ]], dtype=float32)>