In [1]:
import numpy as np

In [2]:
data1 = [6,7.5,8,0,1]
data1

[6, 7.5, 8, 0, 1]

In [3]:
# numpy를 이용하여 1차원 배열로 변형하기
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [4]:
# 배열의 크기 확인
arr1.shape 

(5,)

In [5]:
# 2차원 List
data2 = [
    [1,2,3,4],
    [5,6,7,8]
]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [6]:
# numpy로 2차원 배열로 변형하기
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2.shape

(2, 4)

In [8]:
# 0으로 구성된 1차원 배열 생성
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros([3,5,2])
# page, row, column

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [11]:
# 1로만 구성된 배열생성
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.full(5,10)

array([10, 10, 10, 10, 10])

In [16]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
# 숫자 8로 구성된 3행 5열 배열 생성
np.full((3,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [20]:
# 범위가 있는 배열 생성
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
arr1.dtype

dtype('float64')

In [23]:

arr3 = np.array([1,2,3,4,5],dtype=np.int64)
arr3.dtype

dtype('int64')

In [25]:
# data type을 변경
float_arr1 = arr3.astype(np.float64)
float_arr1.dtype

dtype('float64')

In [26]:
float_arr1

array([1., 2., 3., 4., 5.])

In [28]:
# 연산
arr1 = np.array([[1,2,3],[4,5,6]],dtype=np.float64)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr2 = np.array([[7,8,9],[10,11,12]],dtype=np.float64)
arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [30]:
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [31]:
arr1 - arr2

array([[-6., -6., -6.],
       [-6., -6., -6.]])

In [32]:
arr1 * arr2

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [33]:
arr1 / arr2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [34]:
arr1 *2 

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [35]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [36]:
arr3 = 1/ arr1
arr3

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [37]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr[5]

5

In [39]:
arr[5:9]

array([5, 6, 7, 8])

In [41]:
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [42]:
arr[:5]

array([0, 1, 2, 3, 4])

In [43]:
arr[8:]

array([12,  9])

### 2차원 배열

In [45]:
arr2d = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16],
])
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [46]:
arr2d.dtype

dtype('int64')

In [52]:
# 2번 행의 자료 출력
arr2d[2,:]

array([ 9, 10, 11, 12])

In [53]:
arr2d[:,2]

array([ 3,  7, 11, 15])

In [59]:
# 1에서 2번행의 자료 출력
arr2d[1:3,]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
#3번열의 자료 출력
arr2d[:,3]

array([ 4,  8, 12, 16])

In [63]:
# 0,1 열의 자료 출력
arr2d[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [57]:
# 1행2열의 자료 출력
arr2d[1,2]

7

In [64]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [68]:
arr2d[0:2,1:3] = 0

In [69]:
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

- rand : 0부터 1사이의 균일분포
- randn : 가우시안 표준 정규 분포
- randint : 균일분포의 정수 난수

# Boolean Indexing

In [91]:
names = np.array(['Charles','Kenny','Hayong','Charles','Hanyong','Kenny','Kenny'])
data = np.random.randn(7,4)

In [72]:
names

array(['Charles', 'Kenny', 'Hayong', 'Charles', 'Hanyong', 'Kenny',
       'Kenny'], dtype='<U7')

In [74]:
names.shape

(7,)

In [75]:
data

array([[ 0.04371052, -0.37391667, -0.06584427,  0.27793486],
       [ 1.87791999, -0.54640867, -1.09450013, -0.18320299],
       [ 1.16423908,  0.061954  ,  0.75779957, -0.45400125],
       [ 0.88315541,  1.37020695, -0.33355955, -0.38613532],
       [-0.6304157 ,  0.15395335, -0.10182602, -0.72755875],
       [ 0.39502406, -1.11240965, -0.06904399, -0.58653404],
       [ 1.17055509, -0.59281215, -1.45023101, -2.38410854]])

In [76]:
data.shape

(7, 4)

In [77]:
# Mask를 이용한 추출
names == "Charles"

array([ True, False, False,  True, False, False, False])

In [78]:
data[names == "Charles",:]

array([[ 0.04371052, -0.37391667, -0.06584427,  0.27793486],
       [ 0.88315541,  1.37020695, -0.33355955, -0.38613532]])

In [79]:
data[(names=="Charles")|(names=="Kenny"),:]

array([[ 0.04371052, -0.37391667, -0.06584427,  0.27793486],
       [ 1.87791999, -0.54640867, -1.09450013, -0.18320299],
       [ 0.88315541,  1.37020695, -0.33355955, -0.38613532],
       [ 0.39502406, -1.11240965, -0.06904399, -0.58653404],
       [ 1.17055509, -0.59281215, -1.45023101, -2.38410854]])

In [80]:
data[:]

array([[ 0.04371052, -0.37391667, -0.06584427,  0.27793486],
       [ 1.87791999, -0.54640867, -1.09450013, -0.18320299],
       [ 1.16423908,  0.061954  ,  0.75779957, -0.45400125],
       [ 0.88315541,  1.37020695, -0.33355955, -0.38613532],
       [-0.6304157 ,  0.15395335, -0.10182602, -0.72755875],
       [ 0.39502406, -1.11240965, -0.06904399, -0.58653404],
       [ 1.17055509, -0.59281215, -1.45023101, -2.38410854]])

In [81]:
data[:,3]

array([ 0.27793486, -0.18320299, -0.45400125, -0.38613532, -0.72755875,
       -0.58653404, -2.38410854])

In [85]:
# data의 4번째 열 값중 0보다 작은것의 mask만들기 
data[data[:,3] <0,:]

array([[ 1.87791999, -0.54640867, -1.09450013, -0.18320299],
       [ 1.16423908,  0.061954  ,  0.75779957, -0.45400125],
       [ 0.88315541,  1.37020695, -0.33355955, -0.38613532],
       [-0.6304157 ,  0.15395335, -0.10182602, -0.72755875],
       [ 0.39502406, -1.11240965, -0.06904399, -0.58653404],
       [ 1.17055509, -0.59281215, -1.45023101, -2.38410854]])

In [92]:
# data의 4번째 열의 값이 0보다 작은 data들을 0으로 대체하기
print(data)
print("")
data[data[:,3]<0,:]=0
print("")
print(data)

[[ 0.74130058 -0.34080435 -0.72489631  0.03765689]
 [-0.4274708  -0.42573222 -1.13499777  1.29506261]
 [-0.01581926  0.67882492  0.94259436  0.94486349]
 [ 0.76966307 -1.07758458  0.29870188  0.42051992]
 [-1.85196816  1.02472457  1.15789687 -0.9900918 ]
 [ 0.76015788  0.08123671 -1.81544852 -1.30069431]
 [ 0.45883124  1.12175776  1.57144783 -0.37080391]]


[[ 0.74130058 -0.34080435 -0.72489631  0.03765689]
 [-0.4274708  -0.42573222 -1.13499777  1.29506261]
 [-0.01581926  0.67882492  0.94259436  0.94486349]
 [ 0.76966307 -1.07758458  0.29870188  0.42051992]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]


In [93]:
# 정렬
arr = np.random.rand(8)
arr 

array([0.02985756, 0.10577248, 0.85602168, 0.72269709, 0.98346548,
       0.12685579, 0.67028992, 0.86063513])

In [94]:
# 오름차순 
np.sort(arr)

array([0.02985756, 0.10577248, 0.12685579, 0.67028992, 0.72269709,
       0.85602168, 0.86063513, 0.98346548])

In [95]:
# 내림차순 정렬
np.sort(arr)[::-1]

array([0.98346548, 0.86063513, 0.85602168, 0.72269709, 0.67028992,
       0.12685579, 0.10577248, 0.02985756])

In [100]:
arr = np.random.rand(5,3)
print(arr)


[[0.64290428 0.80746848 0.16516909]
 [0.31831301 0.95767723 0.78362768]
 [0.27174871 0.07057399 0.60767967]
 [0.73825596 0.22207058 0.80714654]
 [0.71830771 0.60997813 0.50956005]]


In [103]:
# 0 : 열방향
print(np.sort(arr,axis=0))
print(np.sort(arr,axis=0)[::-1])


[[0.27174871 0.07057399 0.16516909]
 [0.31831301 0.22207058 0.50956005]
 [0.64290428 0.60997813 0.60767967]
 [0.71830771 0.80746848 0.78362768]
 [0.73825596 0.95767723 0.80714654]]
[[0.73825596 0.95767723 0.80714654]
 [0.71830771 0.80746848 0.78362768]
 [0.64290428 0.60997813 0.60767967]
 [0.31831301 0.22207058 0.50956005]
 [0.27174871 0.07057399 0.16516909]]


In [106]:
# 1 : 행방향
print(np.sort(arr,axis=1))
print(np.sort(arr,axis=1)[:,::-1])

[[0.16516909 0.64290428 0.80746848]
 [0.31831301 0.78362768 0.95767723]
 [0.07057399 0.27174871 0.60767967]
 [0.22207058 0.73825596 0.80714654]
 [0.50956005 0.60997813 0.71830771]]
[[0.80746848 0.64290428 0.16516909]
 [0.95767723 0.78362768 0.31831301]
 [0.60767967 0.27174871 0.07057399]
 [0.80714654 0.73825596 0.22207058]
 [0.71830771 0.60997813 0.50956005]]


In [107]:
# 중복제거 
np.unique(names)

array(['Charles', 'Hanyong', 'Hayong', 'Kenny'], dtype='<U7')

---
# reshape

In [108]:
arr = np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [109]:
arr.shape

(8,)

In [110]:
# 2차원 배열로 변경
arr1 = np.reshape(arr,(2,4))
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [112]:
# 3차원 배열로 변경
arr2 = np.reshape(arr,(2,2,2))
# (page, row, column)
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [127]:
# 2차원 배열을 1차원으로 변경
arr3 =arr1.reshape(1,-1,1)
arr3

array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]]])

In [125]:
# 3차원 배열을 1차원으로 변경 
# arr4 = arr2.reshape(-1 , 1 ,1) # 딥러닝에서는 1을 꼭 표시해줘야한다. (이미지 학습시킬 때) 1차원이라고 차원 수를 꼭 알려줘야한다
# arr4 = arr2.reshape(-1 , 1) 
arr4 = arr2.reshape(-1) # 일반적으로 사용 , 딥러닝에서는 사용하지 못함 
arr4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [128]:
arr3 == arr4

array([[[ True, False, False, False, False, False, False, False],
        [False,  True, False, False, False, False, False, False],
        [False, False,  True, False, False, False, False, False],
        [False, False, False,  True, False, False, False, False],
        [False, False, False, False,  True, False, False, False],
        [False, False, False, False, False,  True, False, False],
        [False, False, False, False, False, False,  True, False],
        [False, False, False, False, False, False, False,  True]]])